# TiDB Cloud Connection
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?ssl-mode=REQUIRED&useUnicode=true&characterEncoding=utf8

# Authentication
spring.datasource.username=etWFyERp9CBoXcs.root
spring.datasource.password=9z5daagMVtRMlcXJ

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver